services:
  - type: web
    name: phonegrade-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5000
    rootDir: backend

  - type: web
    name: phonegrade-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port 8000 --server.headless true
    rootDir: frontend
